language: node_js
services: mongodb
install:
  - npm install
before_script:
  - npm install -g gulp
  - npm install -g mocha
  - npm install -g casperjs
  - npm uninstall -g casperjs
  - npm install -g casperjs
  - casperjs --version
  - npm install -g bower
  - bower install
script: gulp test
